version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins-docker
    user: root
    group_add:
      - 971
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home:z
      - /var/run/docker.sock:/var/run/docker.sock:z
    networks:
      - cicd-net
    labels:
      - "com.example.container_id=jenkins"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  cicd-net:
    external: true
